# An example of the most basic config file we can use with `MKDocs`
# Great place to start to see if this is working / what you need to fix
# or customzie

site_name: Egothare
site_url: https://saurbre8.github.io/Egothare
site_author: Brenden S
site_description: A description of your site
docs_dir: .
site_dir: site
