# An example of the most basic config file we can use with `MKDocs`
# Great place to start to see if this is working / what you need to fix
# or customzie

site_name: Egothare
site_url: https://saurbre8.github.io/Egothare
site_author: Brenden S
site_description: A site for Daggerheart

# Theme configuration
theme:
  name: material  # Popular theme with many customization options
  # Alternative themes: readthedocs, mkdocs, bootstrap, etc.
  
  # Fantasy theme specific options
  palette:
    - scheme: default
      primary: deep purple
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark realm
    - scheme: slate
      primary: deep purple
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light realm
  
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - navigation.instant

  font:
    text: Cinzel
    code: Fira Code

# Custom CSS
extra_css:
  - stylesheets/extra.css

# Extensions for enhanced functionality
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
